/**
 * Generative AI Service
 * LLM kullanarak remediation script'leri, raporlar ve açıklamalar oluşturur
 */

import { logger } from "../utils/logger";

export interface GenerativeScriptRequest {
  imageName: string;
  riskFactors: string[];
  riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  targetEnvironment: "kubernetes" | "docker" | "ci-cd";
  scriptType: "bash" | "kubectl" | "yaml" | "python";
}

export interface GenerativeScriptResponse {
  script: string;
  explanation: string;
  steps: string[];
  warnings: string[];
  estimatedTime: string;
  confidence: number; // 0-1
}

export interface GenerativeReportRequest {
  reportType: "executive" | "technical" | "compliance";
  images: Array<{
    imageName: string;
    riskScore: number;
    riskLevel: string;
    riskFactors: string[];
  }>;
  language?: "tr" | "en";
}

export interface GenerativeReportResponse {
  report: string;
  summary: string;
  keyFindings: string[];
  recommendations: string[];
}

export interface GenerativeCVEDescriptionRequest {
  cveId: string;
  severity: string;
  affectedPackages: string[];
}

export interface GenerativeCVEDescriptionResponse {
  description: string;
  impact: string;
  remediation: string;
  references: string[];
}

export class GenerativeAIService {
  /**
   * LLM kullanarak remediation script'i oluşturur
   */
  async generateRemediationScript(request: GenerativeScriptRequest): Promise<GenerativeScriptResponse> {
    logger.info(`Generative AI ile remediation script oluşturuluyor: ${request.imageName}`);

    // Simüle edilmiş LLM response (gerçek implementasyonda OpenAI, Anthropic, veya local LLM kullanılır)
    const script = this.generateScriptContent(request);
    const explanation = this.generateExplanation(request);
    const steps = this.generateSteps(request);
    const warnings = this.generateWarnings(request);

    return {
      script,
      explanation,
      steps,
      warnings,
      estimatedTime: this.estimateTime(request),
      confidence: 0.85, // LLM confidence score
    };
  }

  /**
   * Script içeriğini oluşturur (LLM simülasyonu)
   */
  private generateScriptContent(request: GenerativeScriptRequest): string {
    let script = "";

    if (request.scriptType === "bash") {
      script = `#!/bin/bash
# Auto-generated remediation script for ${request.imageName}
# Risk Level: ${request.riskLevel}
# Generated by AutoPatch AI Generative AI

set -euo pipefail

echo "Starting remediation for ${request.imageName}..."

`;

      if (request.riskFactors.includes("Uses latest tag")) {
        script += `# Fix: Use versioned tag instead of latest
IMAGE_NAME="${request.imageName.split(":")[0]}"
VERSION="v1.0.0"  # Update this to your desired version
NEW_IMAGE="${IMAGE_NAME}:${VERSION}"

echo "Updating image tag from latest to versioned..."
docker pull ${NEW_IMAGE}
docker tag ${NEW_IMAGE} ${request.imageName}

`;
      }

      if (request.riskFactors.includes("Uses root user")) {
        script += `# Fix: Create non-root user
echo "Creating non-root user..."
docker run --rm ${request.imageName} sh -c "adduser -D -s /bin/sh appuser && chown -R appuser:appuser /app"

`;
      }

      script += `echo "Remediation completed successfully!"
`;
    } else if (request.scriptType === "kubectl") {
      script = `# Auto-generated kubectl remediation script
# Risk Level: ${request.riskLevel}
# Generated by AutoPatch AI Generative AI

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${request.imageName.split("/").pop()?.split(":")[0] || "app"}
spec:
  template:
    spec:
      containers:
      - name: app
        image: ${request.imageName}
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
`;
    }

    return script;
  }

  /**
   * Açıklama oluşturur (LLM simülasyonu)
   */
  private generateExplanation(request: GenerativeScriptRequest): string {
    return `This remediation script addresses ${request.riskFactors.length} risk factor(s) identified in ${request.imageName}. 
The script is designed for ${request.targetEnvironment} environment and will automatically fix the identified security issues.
Risk level: ${request.riskLevel}. Please review the script before execution and test in a non-production environment first.`;
  }

  /**
   * Adımları oluşturur
   */
  private generateSteps(request: GenerativeScriptRequest): string[] {
    const steps: string[] = [
      "Review the generated script",
      "Test in a non-production environment",
      "Backup current configuration",
      "Execute the remediation script",
      "Verify the changes",
      "Monitor for any issues",
    ];

    if (request.riskLevel === "CRITICAL" || request.riskLevel === "HIGH") {
      steps.unshift("Notify stakeholders about the remediation");
    }

    return steps;
  }

  /**
   * Uyarıları oluşturur
   */
  private generateWarnings(request: GenerativeScriptRequest): string[] {
    const warnings: string[] = [];

    if (request.riskLevel === "CRITICAL") {
      warnings.push("This is a critical risk. Immediate action is required.");
    }

    if (request.targetEnvironment === "kubernetes") {
      warnings.push("This script will modify Kubernetes resources. Ensure you have proper backups.");
    }

    if (request.riskFactors.includes("Uses latest tag")) {
      warnings.push("Changing image tags may cause application downtime. Plan accordingly.");
    }

    return warnings;
  }

  /**
   * Tahmini süre hesaplar
   */
  private estimateTime(request: GenerativeScriptRequest): string {
    const baseTime = 5; // minutes
    const factorTime = request.riskFactors.length * 2;
    const totalMinutes = baseTime + factorTime;

    if (totalMinutes < 60) {
      return `${totalMinutes} minutes`;
    }
    return `${Math.floor(totalMinutes / 60)} hour(s) ${totalMinutes % 60} minute(s)`;
  }

  /**
   * Natural language rapor oluşturur (LLM)
   */
  async generateNaturalLanguageReport(request: GenerativeReportRequest): Promise<GenerativeReportResponse> {
    logger.info(`Generative AI ile rapor oluşturuluyor: ${request.reportType}`);

    const report = this.generateReportContent(request);
    const summary = this.generateSummary(request);
    const keyFindings = this.extractKeyFindings(request);
    const recommendations = this.generateRecommendations(request);

    return {
      report,
      summary,
      keyFindings,
      recommendations,
    };
  }

  /**
   * Rapor içeriğini oluşturur (LLM simülasyonu)
   */
  private generateReportContent(request: GenerativeReportRequest): string {
    const language = request.language || "en";
    const totalImages = request.images.length;
    const criticalImages = request.images.filter(img => img.riskLevel === "CRITICAL").length;
    const highRiskImages = request.images.filter(img => img.riskLevel === "HIGH").length;

    if (language === "tr") {
      return `# Container Image Risk Analiz Raporu

Bu rapor, ${totalImages} container image'inin güvenlik risk analizini içermektedir.

## Özet
- Toplam Image: ${totalImages}
- Kritik Risk: ${criticalImages}
- Yüksek Risk: ${highRiskImages}

## Detaylı Analiz
${request.images.map(img => `
### ${img.imageName}
- Risk Skoru: ${img.riskScore}/100
- Risk Seviyesi: ${img.riskLevel}
- Risk Faktörleri: ${img.riskFactors.join(", ")}
`).join("\n")}

## Öneriler
Yukarıdaki risk faktörlerini ele almak için otomatik remediation script'leri oluşturulmuştur.
`;
    } else {
      return `# Container Image Risk Analysis Report

This report contains security risk analysis of ${totalImages} container images.

## Summary
- Total Images: ${totalImages}
- Critical Risk: ${criticalImages}
- High Risk: ${highRiskImages}

## Detailed Analysis
${request.images.map(img => `
### ${img.imageName}
- Risk Score: ${img.riskScore}/100
- Risk Level: ${img.riskLevel}
- Risk Factors: ${img.riskFactors.join(", ")}
`).join("\n")}

## Recommendations
Automated remediation scripts have been generated to address the risk factors above.
`;
    }
  }

  /**
   * Özet oluşturur
   */
  private generateSummary(request: GenerativeReportRequest): string {
    const totalImages = request.images.length;
    const avgRiskScore = request.images.reduce((sum, img) => sum + img.riskScore, 0) / totalImages;

    return `Analysis of ${totalImages} container images reveals an average risk score of ${avgRiskScore.toFixed(1)}/100. 
${request.images.filter(img => img.riskLevel === "CRITICAL" || img.riskLevel === "HIGH").length} images require immediate attention.`;
  }

  /**
   * Ana bulguları çıkarır
   */
  private extractKeyFindings(request: GenerativeReportRequest): string[] {
    const findings: string[] = [];

    const criticalCount = request.images.filter(img => img.riskLevel === "CRITICAL").length;
    if (criticalCount > 0) {
      findings.push(`${criticalCount} images have critical risk levels`);
    }

    const latestTagCount = request.images.filter(img => img.riskFactors.includes("Uses latest tag")).length;
    if (latestTagCount > 0) {
      findings.push(`${latestTagCount} images use 'latest' tag, which is a security risk`);
    }

    const rootUserCount = request.images.filter(img => img.riskFactors.includes("Uses root user")).length;
    if (rootUserCount > 0) {
      findings.push(`${rootUserCount} images run as root user`);
    }

    return findings;
  }

  /**
   * Öneriler oluşturur
   */
  private generateRecommendations(request: GenerativeReportRequest): string[] {
    const recommendations: string[] = [
      "Implement automated scanning in CI/CD pipelines",
      "Use versioned tags instead of 'latest'",
      "Run containers as non-root users",
      "Regularly update base images",
      "Implement security policies and enforce them",
    ];

    if (request.images.some(img => img.riskLevel === "CRITICAL")) {
      recommendations.unshift("Immediate remediation required for critical risk images");
    }

    return recommendations;
  }

  /**
   * CVE açıklaması oluşturur (LLM)
   */
  async generateCVEDescription(request: GenerativeCVEDescriptionRequest): Promise<GenerativeCVEDescriptionResponse> {
    logger.info(`Generative AI ile CVE açıklaması oluşturuluyor: ${request.cveId}`);

    return {
      description: `CVE-${request.cveId} is a ${request.severity} severity vulnerability affecting ${request.affectedPackages.join(", ")}. 
This vulnerability could allow attackers to ${this.getImpactDescription(request.severity)}.`,
      impact: this.getImpactDescription(request.severity),
      remediation: `Update affected packages to patched versions. For ${request.affectedPackages.join(", ")}, 
apply security patches as soon as possible. Consider using automated patch management tools.`,
      references: [
        `https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-${request.cveId}`,
        `https://nvd.nist.gov/vuln/detail/CVE-${request.cveId}`,
      ],
    };
  }

  /**
   * Impact açıklaması oluşturur
   */
  private getImpactDescription(severity: string): string {
    switch (severity.toUpperCase()) {
      case "CRITICAL":
        return "execute arbitrary code, gain full system access, or cause complete system compromise";
      case "HIGH":
        return "gain elevated privileges, access sensitive data, or cause significant system disruption";
      case "MEDIUM":
        return "access limited data or cause moderate system disruption";
      case "LOW":
        return "cause minor system disruption or information disclosure";
      default:
        return "cause security issues";
    }
  }
}

