import Head from "next/head";
import { GetServerSideProps } from "next";
import { useState } from "react";
import MainLayout from "../components/MainLayout";

interface ReportHistoryEntry {
  id: string;
  reportType: string;
  generatedAt: string;
  generatedBy: string;
  format: string;
  size: string;
  downloadUrl?: string;
}

export interface Props {
  history: ReportHistoryEntry[] | null;
  error?: string;
}

export default function ReportHistoryPage({ history, error }: Props) {
  const [filter, setFilter] = useState("all");
  const [searchQuery, setSearchQuery] = useState("");

  const filtered = history?.filter(entry => {
    if (filter !== "all" && entry.reportType !== filter) return false;
    if (searchQuery && !entry.reportType.toLowerCase().includes(searchQuery.toLowerCase())) return false;
    return true;
  }) || [];

  return (
    <MainLayout>
      <Head>
        <title>Report History - AutoPatch AI</title>
      </Head>

      <div style={{ color: "white" }}>
        <h1 style={{ fontSize: "28px", fontWeight: 600, marginBottom: "8px" }}>Report History</h1>
        <p style={{ color: "#9CA3AF", fontSize: "14px", marginBottom: "24px" }}>
          View all previously generated reports
        </p>

        {/* Filters */}
        <div style={{ display: "flex", gap: "12px", marginBottom: "24px" }}>
          <select
            value={filter}
            onChange={(e) => setFilter(e.target.value)}
            style={{
              backgroundColor: "#2D3748",
              border: "1px solid #374151",
              borderRadius: "6px",
              padding: "8px 32px 8px 12px",
              color: "white",
              fontSize: "14px",
              cursor: "pointer",
              outline: "none",
            }}
          >
            <option value="all">All Types</option>
            <option value="risk-summary">Risk Summary</option>
            <option value="executive-summary">Executive Summary</option>
            <option value="compliance">Compliance</option>
            <option value="detailed">Detailed</option>
          </select>
          <input
            type="text"
            placeholder="Search history..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            style={{
              flex: 1,
              maxWidth: "400px",
              backgroundColor: "#2D3748",
              border: "1px solid #374151",
              borderRadius: "6px",
              padding: "8px 12px",
              color: "white",
              fontSize: "14px",
              outline: "none",
            }}
          />
        </div>

        {error && (
          <div style={{ backgroundColor: "#1E293B", borderRadius: "12px", padding: "20px", border: "1px solid #334155", color: "#EF4444" }}>
            Error: {error}
          </div>
        )}

        {!error && filtered.length === 0 && (
          <div style={{ backgroundColor: "#1E293B", borderRadius: "12px", padding: "40px", border: "1px solid #334155", textAlign: "center", color: "#9CA3AF" }}>
            No report history found
          </div>
        )}

        {!error && filtered.length > 0 && (
          <div style={{ backgroundColor: "#1E293B", borderRadius: "12px", border: "1px solid #334155", overflow: "hidden" }}>
            <div style={{ overflowX: "auto" }}>
              <table style={{ width: "100%", borderCollapse: "collapse" }}>
                <thead>
                  <tr style={{ backgroundColor: "#0F172A", borderBottom: "1px solid #334155" }}>
                    <th style={{ padding: "12px 16px", textAlign: "left", fontSize: "12px", fontWeight: 600, color: "#9CA3AF" }}>Generated</th>
                    <th style={{ padding: "12px 16px", textAlign: "left", fontSize: "12px", fontWeight: 600, color: "#9CA3AF" }}>Type</th>
                    <th style={{ padding: "12px 16px", textAlign: "left", fontSize: "12px", fontWeight: 600, color: "#9CA3AF" }}>Generated By</th>
                    <th style={{ padding: "12px 16px", textAlign: "left", fontSize: "12px", fontWeight: 600, color: "#9CA3AF" }}>Format</th>
                    <th style={{ padding: "12px 16px", textAlign: "left", fontSize: "12px", fontWeight: 600, color: "#9CA3AF" }}>Size</th>
                    <th style={{ padding: "12px 16px", textAlign: "center", fontSize: "12px", fontWeight: 600, color: "#9CA3AF" }}>Action</th>
                  </tr>
                </thead>
                <tbody>
                  {filtered.map((entry, idx) => (
                    <tr
                      key={entry.id}
                      style={{
                        borderBottom: idx < filtered.length - 1 ? "1px solid #334155" : "none",
                        transition: "background-color 0.2s",
                      }}
                      onMouseEnter={(e) => {
                        e.currentTarget.style.backgroundColor = "#0F172A";
                      }}
                      onMouseLeave={(e) => {
                        e.currentTarget.style.backgroundColor = "transparent";
                      }}
                    >
                      <td style={{ padding: "12px 16px", color: "#CBD5E0", fontSize: "13px" }}>
                        {new Date(entry.generatedAt).toLocaleString()}
                      </td>
                      <td style={{ padding: "12px 16px", color: "#CBD5E0", fontSize: "13px", textTransform: "capitalize" }}>
                        {entry.reportType.replace("-", " ")}
                      </td>
                      <td style={{ padding: "12px 16px", color: "#CBD5E0", fontSize: "13px" }}>{entry.generatedBy}</td>
                      <td style={{ padding: "12px 16px", color: "#CBD5E0", fontSize: "13px", textTransform: "uppercase" }}>{entry.format}</td>
                      <td style={{ padding: "12px 16px", color: "#CBD5E0", fontSize: "13px" }}>{entry.size}</td>
                      <td style={{ padding: "12px 16px", textAlign: "center" }}>
                        <button
                          style={{
                            backgroundColor: "#2563EB",
                            color: "white",
                            border: "none",
                            borderRadius: "6px",
                            padding: "6px 12px",
                            cursor: "pointer",
                            fontSize: "12px",
                          }}
                        >
                          Download
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </div>
    </MainLayout>
  );
}

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  try {
    const { fetchReportHistory } = await import("../lib/api");
    const historyData = await fetchReportHistory(1, 50);
    const history = historyData.reports.map((r: any) => ({
      id: r._id,
      reportType: r.reportType,
      generatedAt: r.createdAt,
      generatedBy: r.createdBy || "system",
      format: r.format || "pdf",
      size: r.fileSize ? `${(r.fileSize / 1024).toFixed(2)} KB` : "N/A",
      downloadUrl: r.filePath,
    }));
    return { props: { history } };
  } catch (error: any) {
    console.error("Error fetching report history:", error);
    return { props: { history: null, error: error.message || "Failed to fetch report history" } };
  }
};
